apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: workflow-prepare
spec:
  selector:
    matchLabels:
      name: workflow-prepare
  template:
    metadata:
      labels:
        name: workflow-prepare
    spec:
      nodeSelector:
        usedby: ftschirpke
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep infinity
        image: alpine
        name: c1
      initContainers:
      - command:
        - sh
        - -c
        - exit 0
        image: friedricht/nf_wfbench:skip_mem_v11
        imagePullPolicy: IfNotPresent
        name: init0
